import logging
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, cast

import mysql.connector
from mysql.connector.abstracts import MySQLConnectionAbstract
from mysql.connector.pooling import PooledMySQLConnection

from config import DbConfig, MODERATOR_SUFFIX

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class DbSpeaker:
    id: str
    name: str
    photo_url: str
    bio: str
    description: str


@contextmanager
def _connection(cfg: DbConfig) -> Iterator[PooledMySQLConnection | MySQLConnectionAbstract]:
    conn = mysql.connector.connect(
        host=cfg.host,
        database=cfg.database,
        user=cfg.user,
        password=cfg.password,
    )
    try:
        yield conn
    finally:
        conn.close()


def _strip_moderator_suffix(name: str) -> str:
    name = name.strip()
    if name.endswith(MODERATOR_SUFFIX):
        name = name[: -len(MODERATOR_SUFFIX)]
    return name.strip()


def _normalize_name(name: str) -> str:
    """Strip the moderator suffix, collapse whitespace, and casefold for fuzzy name matching.

    Used only for building lookup keys — the raw name is preserved when writing to DB.
    'Nirmal Fernando (Moderator)' and 'Nirmal Fernando' both normalize to the same key.
    """
    return " ".join(_strip_moderator_suffix(name).split()).casefold()


def fetch_existing_speakers(cfg: DbConfig) -> dict[str, DbSpeaker]:
    """Return a normalized-name → DbSpeaker mapping for all rows in the speaker table.

    Keys are normalized so lookup is whitespace- and case-insensitive.
    If the same name appears more than once, the row with the highest numeric id wins —
    that is the row targeted by any subsequent update.
    """
    with _connection(cfg) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT id, name, photoUrl, Bio, description FROM speaker")
        rows = cast(list[tuple[Any, ...]], cursor.fetchall())
        result: dict[str, DbSpeaker] = {}
        for row in rows:
            if not row[1]:
                continue
            key = _normalize_name(row[1])
            speaker = DbSpeaker(
                id=str(row[0]),
                name=row[1],
                photo_url=str(row[2] or ""),
                bio=str(row[3] or ""),
                description=str(row[4] or ""),
            )
            # id is stored as a string but contains a numeric value — compare as int
            # so that "10" beats "9" rather than losing on string order.
            existing = result.get(key)
            if existing is None or int(speaker.id) > int(existing.id):
                result[key] = speaker
        return result


def update_speaker(cfg: DbConfig, db_id: str, new_name: str, photo_url: str, bio: str, description: str) -> None:
    """Overwrite name, photoUrl, Bio, and description for a speaker row, targeted by id.

    Using id as the WHERE target is unambiguous even when duplicate name rows exist
    or the name itself is changing.
    """
    with _connection(cfg) as conn:
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE speaker SET name = %s, photoUrl = %s, Bio = %s, description = %s WHERE id = %s",
            (new_name, photo_url, bio, description, db_id),
        )
        conn.commit()


def insert_speakers(cfg: DbConfig, records: list[dict[str, str]], start_id: int) -> None:
    """Insert new speakers into the DB with explicit ids starting from start_id.

    IDs are assigned sequentially — first record gets start_id, next gets start_id + 1, etc.
    The uuid generated by the scraper is not used; the caller controls the id sequence.
    """
    if not records:
        logger.info("No new speakers to insert")
        return
    rows = [
        (
            start_id + i,
            r.get("name", ""),
            r.get("email", ""),
            r.get("description", ""),
            r.get("photoUrl", ""),
            r.get("Bio", ""),
        )
        for i, r in enumerate(records)
    ]
    with _connection(cfg) as conn:
        cursor = conn.cursor()
        cursor.executemany(
            "INSERT INTO speaker (id, name, email, description, photoUrl, Bio) VALUES (%s, %s, %s, %s, %s, %s)",
            rows,
        )
        conn.commit()
        logger.info("Inserted %d new speaker(s) into DB (ids %d–%d)", len(rows), start_id, start_id + len(rows) - 1)


def reconcile_speakers(
    records: list[dict[str, str]],
    existing: dict[str, DbSpeaker],
    cfg: DbConfig,
) -> list[dict[str, str]]:
    """Return only records whose name was not found in the DB.

    Both match paths (exact or updated) exclude the speaker from the returned
    list — only speakers with no DB match pass through to the CSV.
    """
    new_speakers: list[dict[str, str]] = []
    for r in records:
        name = r.get("name", "")
        db_row = existing.get(_normalize_name(name))
        if db_row is None:
            new_speakers.append(r)
            continue

        new_photo_url = r.get("photoUrl", "")
        new_bio = r.get("Bio", "")
        new_description = r.get("description", "")
        url_changed = new_photo_url != db_row.photo_url
        bio_changed = new_bio != db_row.bio
        description_changed = new_description != db_row.description

        # Raw name comparison catches suffix additions — e.g. CSV has 'Nirmal Fernando (Moderator)'
        # but DB still has 'Nirmal Fernando'. The suffix should be written to the DB.
        name_changed = name != db_row.name
        if name_changed or url_changed or bio_changed or description_changed:
            # db_row.name as the WHERE target ensures the UPDATE hits the right row
            # even when the name itself is changing.
            update_speaker(cfg, db_row.id, name, new_photo_url, new_bio, new_description)
            logger.info("Updated speaker in DB (id=%s): %s → %s", db_row.id, db_row.name, name)
            if url_changed:
                logger.info("  photoUrl (old): %r", db_row.photo_url)
            if bio_changed:
                logger.info("  Bio (old): %r", db_row.bio)
            if description_changed:
                logger.info("  description (old): %r", db_row.description)
        else:
            logger.info("Speaker already in sync, skipping: %s", db_row.name)

    return new_speakers
