import logging
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, cast

import mysql.connector
from mysql.connector.abstracts import MySQLConnectionAbstract
from mysql.connector.pooling import PooledMySQLConnection

from config import DbConfig

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class DbSpeaker:
    name: str
    photo_url: str
    bio: str
    description: str


@contextmanager
def _connection(cfg: DbConfig) -> Iterator[PooledMySQLConnection | MySQLConnectionAbstract]:
    conn = mysql.connector.connect(
        host=cfg.host,
        database=cfg.database,
        user=cfg.user,
        password=cfg.password,
    )
    try:
        yield conn
    finally:
        conn.close()


def _normalize_name(name: str) -> str:
    """Strip, collapse internal whitespace, and casefold for fuzzy name matching.

    Handles names like 'Dr. Rania Khalaf' matching ' dr. rania khalaf '.
    """
    return " ".join(name.strip().split()).casefold()


def fetch_existing_speakers(cfg: DbConfig) -> dict[str, DbSpeaker]:
    """Return a normalized-name → DbSpeaker mapping for all rows in the speaker table.

    Keys are normalized so lookup is whitespace- and case-insensitive.
    The original DB name is preserved in DbSpeaker.name for UPDATE queries.
    """
    with _connection(cfg) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name, photoUrl, Bio, description FROM speaker")
        # cast: non-dict cursor returns tuples; Pylance sees a broader union without it
        rows = cast(list[tuple[Any, ...]], cursor.fetchall())
        return {
            _normalize_name(row[0]): DbSpeaker(
                name=row[0],
                photo_url=str(row[1] or ""),
                bio=str(row[2] or ""),
                description=str(row[3] or ""),
            )
            for row in rows
            if row[0]
        }


def update_speaker(cfg: DbConfig, db_name: str, photo_url: str, bio: str, description: str) -> None:
    """Overwrite photoUrl, Bio, and description for an existing speaker row, matched by original DB name."""
    with _connection(cfg) as conn:
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE speaker SET photoUrl = %s, Bio = %s, description = %s WHERE name = %s",
            (photo_url, bio, description, db_name),
        )
        conn.commit()


def insert_speakers(cfg: DbConfig, records: list[dict[str, str]], start_id: int) -> None:
    """Insert new speakers into the DB with explicit ids starting from start_id.

    IDs are assigned sequentially — first record gets start_id, next gets start_id + 1, etc.
    The uuid generated by the scraper is not used; the caller controls the id sequence.
    """
    if not records:
        logger.info("No new speakers to insert")
        return
    rows = [
        (
            start_id + i,
            r.get("name", ""),
            r.get("email", ""),
            r.get("description", ""),
            r.get("photoUrl", ""),
            r.get("Bio", ""),
        )
        for i, r in enumerate(records)
    ]
    with _connection(cfg) as conn:
        cursor = conn.cursor()
        cursor.executemany(
            "INSERT INTO speaker (id, name, email, description, photoUrl, Bio) VALUES (%s, %s, %s, %s, %s, %s)",
            rows,
        )
        conn.commit()
        logger.info("Inserted %d new speaker(s) into DB (ids %d–%d)", len(rows), start_id, start_id + len(rows) - 1)


def reconcile_speakers(
    records: list[dict[str, str]],
    existing: dict[str, DbSpeaker],
    cfg: DbConfig,
) -> list[dict[str, str]]:
    """Return only records whose name was not found in the DB.

    Both match paths (exact or updated) exclude the speaker from the returned
    list — only speakers with no DB match pass through to the CSV.
    """
    new_speakers: list[dict[str, str]] = []
    for r in records:
        name = r.get("name", "")
        db_row = existing.get(_normalize_name(name))
        if db_row is None:
            new_speakers.append(r)
            continue

        new_photo_url = r.get("photoUrl", "")
        new_bio = r.get("Bio", "")
        new_description = r.get("description", "")
        url_changed = new_photo_url != db_row.photo_url
        bio_changed = new_bio != db_row.bio
        description_changed = new_description != db_row.description

        if url_changed or bio_changed or description_changed:
            # Use db_row.name (original DB value) as WHERE target to avoid a missed
            # UPDATE from minor formatting differences in the scraped name.
            update_speaker(cfg, db_row.name, new_photo_url, new_bio, new_description)
            logger.info("Updated speaker in DB: %s", db_row.name)
            if url_changed:
                logger.info("  photoUrl (old): %r", db_row.photo_url)
            if bio_changed:
                logger.info("  Bio (old): %r", db_row.bio)
            if description_changed:
                logger.info("  description (old): %r", db_row.description)
        else:
            logger.info("Speaker already in sync, skipping: %s", db_row.name)

    return new_speakers
